### ISSUE TITLE
Google Translate issue? ... How to fix?

### ISSUE THREAD

**Issue by DanFlorianm** [mxrch/darkshot#10]
C:\Users\DAN\Desktop\darkshot-master>python run.py -t 5 -m stealth -a descending

Translation of keywords...
Traceback (most recent call last):
  File "C:\Users\DAN\Desktop\darkshot-master\run.py", line 55, in <module>
    start()
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\DAN\Desktop\darkshot-master\run.py", line 52, in start
    main(threads, mode, algo, debug, clean, resume_ro)
  File "C:\Users\DAN\Desktop\darkshot-master\main.py", line 44, in main
    words = translate_keywords(cfg["keywords_langs"], cfg["words_to_translate"])
  File "C:\Users\DAN\Desktop\darkshot-master\lib\translate.py", line 9, in translate_keywords
    translation = translator.translate(word, lang_tgt=code)
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\site-packages\google_trans_new\google_trans_new.py", line 188, in translate
    raise e
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\site-packages\google_trans_new\google_trans_new.py", line 152, in translate
    response = json.loads(response)
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\DAN\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1030 (char 1029)

### I get this error while trying to run it simple as it comes out of the ZIP file. It cannot even start..
**python run.py -t 5 -m stealth -a descending**

**Comment by DanFlorianm** [comment]
Fixed by downloading the new and updated .zip file!
