### ISSUE TITLE
Noisy mode error?

### ISSUE THREAD

**Issue by Frigyes06** [mxrch/darkshot#19]
Translation of keywords...
Getting the last seen link...
Traceback (most recent call last):
  File "run.py", line 57, in <module>
    start()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 54, in start
    main(threads, mode, algo, debug, clean, resume_ro)
  File "/home/frigyes/Desktop/darkshot/main.py", line 54, in main
    limit = get_limit(mode, client)
  File "/home/frigyes/Desktop/darkshot/lib/get_limit.py", line 49, in get_limit
    out = noisy()
  File "/home/frigyes/Desktop/darkshot/lib/get_limit.py", line 32, in noisy
    req = client.post("https://prntscr.com/upload.php", files=files, headers=headers)
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpx/_client.py", line 824, in post
    return self.request(
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpx/_client.py", line 600, in request
    return self.send(
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpx/_client.py", line 620, in send
    response = self.send_handling_redirects(
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpx/_client.py", line 647, in send_handling_redirects
    response = self.send_handling_auth(
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpx/_client.py", line 684, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpx/_client.py", line 714, in send_single_request
    ) = transport.request(
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 152, in request
    response = connection.request(
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 78, in request
    return self.connection.request(method, url, headers, stream, timeout)
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 62, in request
    ) = self._receive_response(timeout)
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 115, in _receive_response
    event = self._receive_event(timeout)
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 145, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/frigyes/.local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ReadTimeout: The read operation timed out

Am I blocked by lightshot?

**Comment by Frigyes06** [comment]
Nvm, temporary issue
