### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by PinkDev1** [mxrch/darkshot#2]
Python 3.8.5
Kali GNU/Linux Rolling x86_64

I've already run `sudo darkshot-venv/bin/python3 check_ocr_langs.py`

When running run.py, I get the following:
```
(darkshot-venv) kali@kali:~/software/darkshot$ python3 run.py 

Traceback (most recent call last):
  File "run.py", line 55, in <module>
    start()
  File "/home/kali/software/darkshot/darkshot-venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kali/software/darkshot/darkshot-venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kali/software/darkshot/darkshot-venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kali/software/darkshot/darkshot-venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "run.py", line 52, in start
    main(threads, mode, algo, debug, clean, resume_ro)
  File "/home/kali/software/darkshot/main.py", line 27, in main
    log(f"Debug mode : {'ACTIVATED' if debug else 'DEACTIVATED'}", timecode=dirname, cfg=cfg, level="VALUABLE", hidden=False, debug=debug)
  File "/home/kali/software/darkshot/lib/log.py", line 28, in log
    with open(path, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/2020-10-06_202859.txt'
```

help pls

**Comment by PinkDev1** [comment]
nvm. I just had to create a folder called `logs` on the same dir as `run.py`.
