### ISSUE TITLE
Can we fix this

### ISSUE THREAD

**Issue by MrHarshvardhan** [mxrch/darkshot#3]
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from main import main
  File "/root/darkshot/main.py", line 27
    log(f"Debug mode : {'ACTIVATED' if debug else 'DEACTIVATED'}", timecode=dirname, cfg=cfg, level="VALUABLE", hidden=False, debug=debug)
                                                                ^
SyntaxError: invalid syntax

**Comment by BobNiko** [comment]
+1 the same issue

**Comment by mxrch** [comment]
You are not using an enough recent version of Python, so it doesn't supports f-strings.
